language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
env:
  matrix:
    - DEVISE_ORM=mongoid
    - DEVISE_ORM=active_record
  global:
    # AMAZON_S3_BUCKET
    - secure: "qkeYGn2mpgsgU5tKS9GWvFp/utUF/9O8++Shch24DMnq8OB01TrV5QQ2Elj7sSjMWqw2Pbe56nUCA9eOWXhPglGyIq2AI9E0umsEGZxdRlqqobpiMWs5wl8KZ0cFD1rZm6CwfL8atmcNfTt5TnvsaQ2l/k3TerOT2e66R/Mibk8="
    # AMAZON_ACCESS_KEY_ID
    - secure: "rTYGUFH9SPN0L7QtdE6Liyy/1z7nGKxqDF9LMRsmNsIfsqxoTPKZ8bCctQ4ksuk9svynGQsLfsda5pA+YvuALzjdWmGcID6ENgOGvoFnhZO5LuJ5f6t0k8gFpV9oBquQgDWzhzrcPYvCUrUYg3GSlHjFSXdPdht3SoYn7PiDaNs="
    # AMAZON_SECRET_ACCESS_KEY
    - secure: "VJ4qiWMzoleLojCcluX+w0RtaFVc9ybRNo6NODkGhHSaao8+4EX4rETBQG67tNSInk1iuNqCcZAGwC8V/12RXdao3PguRSLD5IiKeT+D78dqFEoP0+yHg4PbmZ6TJXADW3gUv/IOqkW7f/UYGinRaPu7hloyiC498FpQdmMWSNI="
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-6.0-beta
  - gemfiles/Gemfile.rails-5.2-stable
  - gemfiles/Gemfile.rails-5.0-stable
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-4.1-stable

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-6.0-beta
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.2-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.0-stable
    - rvm: 2.2.10
      gemfile: Gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-6.0-beta
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.2-stable
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-6.0-beta
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-6.0-beta
    - rvm: 2.5.3
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: 2.6.0
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: 2.6.0
      gemfile: gemfiles/Gemfile.rails-4.2-stable
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-4.1-stable
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-4.2-stable
    - env: DEVISE_ORM=mongoid
      gemfile: Gemfile
    - env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-5.0-stable
    - env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-5.2-stable
    - env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-6.0-beta
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile.rails-6.0-beta

services:
  - mongodb

sudo: false

cache: bundler

env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: "bin/test"

notifications:
  email: false
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    secure: Q3M+kmude3FjisibEeeGe0wSMXgvwLH+vL7Zrx9//q4QtkfnrQ/BBMvY9KXxPEsNF+eys4YopYjTkJ8uRmeboUATW/oQ4Jrv3+u3zkIHK2sFn/Q2cQWpK5w+CbgEnHPjKYnUu34b09njXTgDlr/mqtbPqrKeZ1dLlpKXCB/q4GY=
